# Generated by Django 5.0.8 on 2024-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='strip_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
